from __future__ import annotations

import secrets
from pathlib import Path


def validate_data_dir(path: str) -> str | None:
    """Return None if the path is usable, or an error string if not."""
    p = Path(path).expanduser()
    if p.exists() and any(p.iterdir()):
        return (
            "That directory already contains files. "
            "Choose an empty folder — Verdikt will manage everything inside it."
        )
    return None


def write_env(
    compose_file: str,
    port: int,
    data_dir: str,
    dist_dir: Path,
    jwt_secret: str | None = None,
) -> None:
    """Write distribution/.env with compose substitution vars + app config.

    Docker Compose auto-loads .env from the same directory as the compose file,
    so this single file drives both bind-mount paths and in-container settings.
    An existing JWT secret is preserved across re-runs.
    """
    env_path = dist_dir / ".env"
    data_dir_abs = str(Path(data_dir).expanduser().resolve())

    # Preserve existing JWT secret on re-run
    secret = jwt_secret
    if not secret and env_path.exists():
        for line in env_path.read_text().splitlines():
            if line.startswith("VERDIKT_JWT_SECRET="):
                secret = line.split("=", 1)[1].strip()
                break

    if not secret:
        secret = secrets.token_hex(32)

    Path(data_dir_abs).mkdir(parents=True, exist_ok=True)

    content = (
        "# Generated by Verdikt installer — do not edit by hand\n"
        f"VERDIKT_HOST_DATA_DIR={data_dir_abs}\n"
        f"VERDIKT_PORT={port}\n"
        f"VERDIKT_JWT_SECRET={secret}\n"
        f"VERDIKT_APP_BASE_URL=http://localhost:{port}\n"
        f'VERDIKT_CORS_ORIGINS=["http://localhost:{port}"]\n'
    )
    env_path.write_text(content)
