#!/usr/bin/env bash
# Verdikt Linux installer
#
# Usage:
#   bash install.sh [--data-dir DIR] [--port PORT] [--no-tray]
#
# Requirements: Docker, Python 3.9+
# The script asks you to choose a model backend (native Ollama / Docker Ollama / cloud)
# and validates that the chosen data directory is empty before writing anything.

set -euo pipefail

DATA_DIR="${VERDIKT_DATA_DIR:-$HOME/VerdiktData}"
PORT="${VERDIKT_PORT:-8765}"
INSTALL_TRAY=true

# ---------- arg parsing ----------
while [[ $# -gt 0 ]]; do
    case $1 in
        --data-dir) DATA_DIR="$2"; shift 2;;
        --port)     PORT="$2";     shift 2;;
        --no-tray)  INSTALL_TRAY=false; shift;;
        *) shift;;
    esac
done

_ok()   { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
_step() { printf '\033[1;34m→\033[0m %s\n' "$*"; }
_err()  { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; }
_ask()  { printf '\033[1;33m?\033[0m %s ' "$*"; }

# ---------- Docker check ----------
_step "Checking Docker…"
if ! docker version >/dev/null 2>&1; then
    _err "Docker is not running."
    _err "Install from: https://docs.docker.com/engine/install/"
    exit 1
fi
_ok "Docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo 'OK')"

# ---------- data dir validation ----------
DATA_DIR="$(realpath -m "$DATA_DIR")"
if [[ -d "$DATA_DIR" ]] && [[ -n "$(ls -A "$DATA_DIR" 2>/dev/null)" ]]; then
    _err "Data directory '$DATA_DIR' is not empty."
    _err "Choose an empty folder — Verdikt manages everything inside it."
    exit 1
fi

# ---------- model backend choice ----------
_step "Checking Ollama…"
if curl -s --max-time 1 http://localhost:11434/api/version >/dev/null 2>&1; then
    _ok "Ollama detected locally"
    COMPOSE_FILE="compose.native-ollama.yml"
else
    echo "  Ollama not found. How should Verdikt access AI models?"
    echo "  1) Run Ollama in Docker  (recommended — downloads ~4 GB Ollama image)"
    echo "  2) Cloud AI only         (Venice / OpenRouter — configure keys after setup)"
    _ask "Choice [1/2, default 1]:"
    read -r choice
    case "${choice:-1}" in
        2) COMPOSE_FILE="compose.no-ollama.yml";;
        *) COMPOSE_FILE="compose.docker-ollama.yml";;
    esac
fi
_ok "Using $COMPOSE_FILE"

# ---------- install files ----------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INSTALL_DIR="$HOME/.local/share/verdikt"

_step "Installing files to $INSTALL_DIR…"
mkdir -p "$INSTALL_DIR"
# Copy the distribution/ tree (compose files, wizard, tray, assets)
rsync -a --exclude='build' --exclude='dist' --exclude='__pycache__' \
    "$SCRIPT_DIR/" "$INSTALL_DIR/" 2>/dev/null || \
    cp -r "$SCRIPT_DIR/." "$INSTALL_DIR/"
_ok "Files installed"

# ---------- write .env ----------
_step "Writing configuration…"
JWT_SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
mkdir -p "$DATA_DIR"

cat > "$INSTALL_DIR/.env" <<ENV
# Generated by Verdikt installer
VERDIKT_HOST_DATA_DIR=$DATA_DIR
VERDIKT_PORT=$PORT
VERDIKT_JWT_SECRET=$JWT_SECRET
VERDIKT_APP_BASE_URL=http://localhost:$PORT
VERDIKT_CORS_ORIGINS=["http://localhost:$PORT"]
ENV
_ok "Configuration written"

# ---------- tray setup ----------
if $INSTALL_TRAY; then
    _step "Installing tray launcher dependencies…"
    pip3 install --user --quiet pystray Pillow

    # Write tray config
    python3 - <<PYEOF
import json
from pathlib import Path
Path.home().joinpath('.verdikt_tray.json').write_text(json.dumps({
    'compose_file': '$INSTALL_DIR/$COMPOSE_FILE',
    'distribution_dir': '$INSTALL_DIR',
    'port': $PORT,
}, indent=2))
PYEOF

    # Systemd user service
    _step "Installing systemd user service…"
    mkdir -p "$HOME/.config/systemd/user"
    PYTHON3="$(which python3)"
    cat > "$HOME/.config/systemd/user/verdikt-tray.service" <<SERVICE
[Unit]
Description=Verdikt System Tray
After=graphical-session.target

[Service]
ExecStart=$PYTHON3 -m tray
WorkingDirectory=$INSTALL_DIR
Restart=on-failure

[Install]
WantedBy=default.target
SERVICE

    systemctl --user daemon-reload
    systemctl --user enable verdikt-tray.service
    _ok "Systemd user service installed (verdikt-tray)"
fi

# ---------- pull and start ----------
_step "Pulling Verdikt image…"
docker compose -f "$INSTALL_DIR/$COMPOSE_FILE" --project-directory "$INSTALL_DIR" pull --quiet
_step "Starting Verdikt…"
docker compose -f "$INSTALL_DIR/$COMPOSE_FILE" --project-directory "$INSTALL_DIR" up -d

echo ""
_ok "Verdikt is running at http://localhost:$PORT"
echo ""
echo "  Open in browser:     http://localhost:$PORT"
if $INSTALL_TRAY; then
echo "  Start tray icon:     systemctl --user start verdikt-tray"
fi
echo "  Stop Verdikt:        docker compose -f $INSTALL_DIR/$COMPOSE_FILE down"
echo ""
